language: node_js
node_js:
  - "12"
dist: trusty
services:
  - mongodb
env:
  - NODE_ENV=test PORT=4444 DATABASE_NAME=travis-test DATABASE_CONNECTING_STRING=mongodb://localhost REGISTER_TOKEN=reg_token SESSION_SECRET=secret
cache:
  directories:
    - node_modules
    - client/node_modules
install:
  - npm install
  - cd client
  - npm install
script:
  - npm run lint
  - npm run test
  - cd client
  - npm run lint
  - npm run test