language: node_js
node_js:
  - "12"
dist: trusty
services:
  - mongodb
env:
  - NODE_ENV=test PORT=4444 DATABASE_NAME=travis-test DATABASE_CONNECTING_STRING=mongodb://localhost REGISTER_TOKEN=reg_token SESSION_SECRET=secret
cache:
  directories:
    - node_modules
    - client/node_modules
matrix:
  fast_finish: true
  include:
    - env: NodeJS
      before_script:
        - npm install
      script:
        - npm run lint
        - npm test
    - env: React
      before_script:
        - cd client
        - npm install
      script:
        - npm run lint
        - npm test
