language: node_js
node_js:
  - "11"
dist: trusty
services:
  - mongodb
env:
  - NODE_ENV=test PORT=4444
cache:
  directories:
    - node_modules
install:
  - npm install
script:
  - npm run lint
  - npm run test