const DRUG_TYPES = [
    'capsule',
    'tablet',
    'injection',
    'powder',
    'ointment',
    'cream', 
    'gel', 
    'solution', 
    'tincture', 
    'suspension', 
    'drops', 
    'syrup', 
    'aerosol', 
    'other',
  ];
  
  const DRUG_CLASSES = [
    'antibacterial_drugs', 
    'hormones', 
    'drugs_affecting_immunity', 
    'drugs_affecting_metabolism', 
    'drugs_affecting_the_psyche', 
    'drugs_affecting_blood_clotting',
    'drugs_affecting_vascular_tone', 
    'drugs_affecting_the_function_of_the_bronchi', 
    'antiparasitic_and_antihelminthic_drugs', 
    'drugs_affecting_the_function_of_the_gastrointestinal_tract', 
    'drugs_affecting_myocardial_function', 
    'drugs_affecting_renal_function', 
    'antiviral_drugs', 
    'antiinflammatory_and_pain_relievers',
    'antifungal_drugs', 
    'antineoplastic_drugs', 
    'other',
  ];