const allowedLanguages = ['en', 'ru'];

const translates = {
  medicinesTypes: {
    en: {
      capsule: 'Capsule',
      tablet: 'Tablet',
      injection: 'Injection',
      powder: 'Powder',
      ointment: 'Ointment',
      cream: 'Cream',
      gel: 'Gel',
      solution: 'Solution',
      tincture: 'Tincture',
      suspension: 'Suspension',
      drops: 'Drops',
      syrup: 'Syrup',
      aerosol: 'Aerosol',
      other: 'Other',
    },
    ru: {
      capsule: 'Капсулы',
      tablet: 'Таблетки',
      injection: 'Инъекции',
      powder: 'Порошок',
      ointment: 'Мазь',
      cream: 'Крем',
      gel: 'Гель',
      solution: 'Раствор',
      tincture: 'Настойка',
      suspension: 'Суспензия',
      drops: 'Капли',
      syrup: 'Сипор',
      aerosol: 'Аэрозоль',
      other: 'Другое',
    },
  },
  medicinesClasses: {
    en: {
      antibacterial_drugs: 'Antibacterial drugs',
      hormones: 'Hormones',
      drugs_affecting_immunity: 'Drugs affecting immunity',
      drugs_affecting_the_psyche: 'Drugs affecting the psyche',
      drugs_affecting_blood_clotting: 'Drugs affecting blood clotting',
      drugs_affecting_vascular_tone: 'Drugs affecting vascular tone',
      drugs_affecting_the_respiratory_system: 'Drugs affecting the respiratory system',
      antiparasitic_and_antihelminthic_drugs: 'Antiparasitic and antihelminthic drugs',
      drugs_affecting_the_function_of_the_gastrointestinal_tract: 'Drugs affecting the function of the gastrointestinal tract',
      drugs_affecting_myocardial_function: 'Drugs affecting myocardial function',
      drugs_affecting_renal_function: 'Drugs affecting renal function',
      drugs_affecting_liver_function: 'Drugs affecting liver function',
      antiviral_drugs: 'Antiviral drugs',
      antiinflammatory_and_pain_relievers: 'Antiinflammatory and pain relievers',
      antifungal_drugs: 'Antifungal drugs',
      antineoplastic_drugs: 'Antineoplastic drugs',
      other: 'Other',
    },
    ru: {
      antibacterial_drugs: 'Антибактериальные препараты',
      hormones: 'Гормональные препараты',
      drugs_affecting_immunity: 'Препараты, влияющие на иммунитет',
      drugs_affecting_the_psyche: 'Препараты, влияющие на психику',
      drugs_affecting_blood_clotting: 'Препараты, влияющие на кроветворение и кровь',
      drugs_affecting_vascular_tone: 'Препараты для лечения заболеваний сосудистой системы',
      drugs_affecting_the_respiratory_system: 'Препараты для лечения заболеваний респираторной системы',
      antiparasitic_and_antihelminthic_drugs: 'Противопаразитарные и противоглистные препараты',
      drugs_affecting_the_function_of_the_gastrointestinal_tract: 'Препараты, влияющие на функцию желудочно-кишечного тракта',
      drugs_affecting_myocardial_function: 'Препараты для лечения заболеваний сердца',
      drugs_affecting_renal_function: 'Препараты, влияющие на функцию почек',
      drugs_affecting_liver_function: 'Препараты, влияющие на функцию печени',
      antiviral_drugs: 'Противовирусные препараты',
      antiinflammatory_and_pain_relievers: 'Противовоспалительные и болеутоляющие',
      antifungal_drugs: 'Противогрибковые препараты',
      antineoplastic_drugs: 'Противоопухолевые препараты',
      other: 'Другое',
    },
  },
};

module.exports = {
  allowedLanguages,
  translates,
};
